<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Views\LoginView\Assets\JB.jpg" />
    <None Remove="Views\LoginView\Assets\loginbackground.png" />
    <None Remove="Views\LoginView\Assets\yuhan.png" />
    <None Remove="Views\LoginView\Assets\로그인배경.png" />
    <None Remove="Views\LoginView\Assets\유한대학교 로고.png" />
    <None Remove="Views\LoginView\Assets\유한대학교로고.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Views\LoginView\Assets\loginbackground.png" />
    <Resource Include="Views\LoginView\Assets\yuhan.png" />
  </ItemGroup>

</Project>
